version: '3.7'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: siswa-app
    container_name: siswa_app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    ports:
      - 8100:8100 
    networks:
      - bridge-network

networks:
  bridge-network:
    driver: bridge
